platform: linux
image_resource:
  { type: docker-image, source: { repository: vcpici/vcpi-main } }
inputs:
- name: source-ci
- name: bosh-cpi-src
- name: version-semver
outputs:
- name: dev-artifacts
run:
  path: source-ci/ci/tasks/build-candidate.sh
