---
platform: linux
image_resource:
  { type: docker-image, source: { repository: vcpici/vcpi-main } }

inputs:
  - name: source-ci
  - name: bosh-cpi-src
  - name: bosh-cpi-artifacts
  - name: release-version-semver

outputs:
  - name: updated-repo
  - name: integer-version

run:
  path: source-ci/ci/tasks/promote-candidate.sh

params:
  AWS_ACCESS_KEY_ID:     ""
  AWS_SECRET_ACCESS_KEY: ""
