platform: linux
image_resource:
  { type: docker-image, source: { repository: vcpici/vcpi-main } }

inputs:
  - name: source-ci
  - name: certification
  - name: environment
  - name: bats
  - name: director-state
  - name: bosh-cli
  - name: stemcell
  - name: bosh-cpi-src

run:
  path: source-ci/ci/tasks/run-bats.sh

params:
  STEMCELL_NAME:      ""
  BAT_RSPEC_FLAGS:    ""
