platform: linux
image_resource:
  { type: docker-image, source: { repository: vcpici/vcpi-main } }

inputs:
  - name: bosh-linux-stemcell-builder
  - name: certification
  - name: bosh-cli
  - name: stemcell
  - name: syslog-release
  - name: os-conf-release
  - name: director-state
  - name: source-ci
  - name: environment

params:
  BOSH_os_name: required
  package: .

run:
  path: source-ci/ci/tasks/test-stemcell.sh